// Metadata created by nebel
//
// ConvertedFromTitle: Pluggable vs Non-Pluggable databases
// ConvertedFromFile: modules/ROOT/pages/connectors/oracle.adoc
// ConversionStatus: raw
// ConvertedFromID: pluggable-vs-non-pluggable-databases

[id="configuration-of-container-databases-and-non-container-databases"]
= Configuration of container databases and non-container-databases
[[oracle-database-mode]]


Oracle Database supports the following deployment types:

Container database (CDB):: A database that can contain multiple pluggable databases (PDBs).
Database clients connect to each PDB as if it were a standard, non-CDB database.

Non-container database (non-CDB):: A standard Oracle database, which does not support the creation of pluggable databases.



For the complete list of the configuration properties that you can set for the {prodname} Oracle connector, see xref:{link-oracle-connector}#oracle-connector-properties[Oracle connector properties].


.Results

After the connector starts, it xref:{link-oracle-connector}#oracle-snapshots[performs a consistent snapshot] of the Oracle databases that the connector is configured for.
The connector then starts generating data change events for row-level operations and streaming the change event records to Kafka topics.

