// Metadata created by nebel
//
// ConvertedFromTitle: Redo log sizing
// ConvertedFromFile: modules/ROOT/pages/connectors/oracle.adoc
// ConversionStatus: raw
// ConvertedFromID: oracle-redo-log-sizing

[id="resizing-oracle-redo-logs-to-accommodate-the-data-dictionary"]
= Resizing-oracle-redo-logs-to-accommodate-the-data-dictionary

Depending on the database configuration, the size and number of redo logs might not be sufficient to achieve acceptable performance.
Before you set up the {prodname} Oracle connector, ensure that the capacity of the redo logs is sufficient to support the database.

The capacity of the redo logs for a database must be sufficient to store its data dictionary.
In general, the size of the data dictionary increases with the number of tables and columns in the database.
If the redo log lacks sufficient capacity, both the database and the {prodname} connector might experience performance problems.

Consult with your database administrator to evaluate whether the database might require increased log capacity.

