// Metadata created by nebel
//
// ConversionStatus: raw
// ConvertedFromID: pluggable-vs-non-pluggable-databases
// ConvertedFromFile: modules/ROOT/pages/connectors/oracle.adoc
// ConvertedFromTitle: Pluggable vs Non-Pluggable databases

[id="configuration-of-container-databases-and-non-container-databases"]
= Configuration of container databases and non-container-databases
[[oracle-database-mode]]


Oracle Database supports the following deployment types:

Container database (CDB):: A database that can contain multiple pluggable databases (PDBs).
Database clients connect to each PDB as if it were a standard, non-CDB database.

Non-container database (non-CDB):: A standard Oracle database, which does not support the creation of pluggable databases.


ifdef::community[]


.Example: {prodname} connector configuration for CDB deployments
[source,json,indent=0]
----
{
  "config": {
    "connector.class" : "io.debezium.connector.oracle.OracleConnector",
    "tasks.max" : "1",
    "database.server.name" : "server1",
    "database.hostname" : "<oracle ip>",
    "database.port" : "1521",
    "database.user" : "c##dbzuser",
    "database.password" : "dbz",
    "database.dbname" : "ORCLCDB",
    "database.pdb.name" : "ORCLPDB1",
    "database.history.kafka.bootstrap.servers" : "kafka:9092",
    "database.history.kafka.topic": "schema-changes.inventory"
  }
}
----

[IMPORTANT]
====
When you configure a {prodname} Oracle connector for use with an Oracle CDB, you must specify a value for the property `database.pdb.name`, which names the PDB that you want the connector to capture changes from.
For non-CDB installation, do *not* specify the `database.pdb.name` property.
====

.Example: {prodname} Oracle connector configuration for non-CDB deployments
[source,json,indent=0]
----
{
    "config": {
        "connector.class" : "io.debezium.connector.oracle.OracleConnector",
        "tasks.max" : "1",
        "database.server.name" : "server1",
        "database.hostname" : "<oracle ip>",
        "database.port" : "1521",
        "database.user" : "c##dbzuser",
        "database.password" : "dbz",
        "database.dbname" : "ORCLCDB",
        "database.history.kafka.bootstrap.servers" : "kafka:9092",
        "database.history.kafka.topic": "schema-changes.inventory"
    }
}
----

endif::community[]

For the complete list of the configuration properties that you can set for the {prodname} Oracle connector, see xref:{link-oracle-connector}#oracle-connector-properties[Oracle connector properties].

ifdef::community[]
You can send this configuration with a `POST` command to a running Kafka Connect service.
The service records the configuration and starts a connector task that performs the following operations:

* Connects to the Oracle database.
* Reads the redo log.
* Records change events to Kafka topics.

