// Metadata created by nebel
//
// ConvertedFromTitle: Preparing the database
// ConvertedFromFile: modules/ROOT/pages/connectors/oracle.adoc
// ConversionStatus: raw

[id="preparing-oracle-databases-for-use-with-debezium"]
= Preparing Oracle databases for use with {prodname}

.Configuration needed for Oracle LogMiner
[source,indent=0]
----
ORACLE_SID=ORACLCDB dbz_oracle sqlplus /nolog

CONNECT sys/top_secret AS SYSDBA
alter system set db_recovery_file_dest_size = 10G;
alter system set db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' scope=spfile;
shutdown immediate
startup mount
alter database archivelog;
alter database open;
-- Should now "Database log mode: Archive Mode"
archive log list

exit;
----

To enable {prodname} to capture the _before_ state of changed database rows, you must also enable supplemental logging for captured tables or for the entire database.
The following example illustrates how to configure supplemental logging for all columns in a single `inventory.customers` table.

[source,indent=0]
----
ALTER TABLE inventory.customers ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
----

Enabling supplemental logging for all table columns increases the volume of the Oracle redo logs.
To prevent excessive growth in the size of the logs, apply the preceding configuration selectively.

Minimal supplemental logging must be enabled at the database level and can be configured as follows.

[source,indent=0]
----
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
----

